### ISSUE TITLE
emacs-document.el emacs-document-start-translation issue

### ISSUE THREAD

**Issue by Faijister** [lujun9972/emacs-document-flow.el#1]
Loading battery...done
Loading time...done
For information about GNU Emacs and the GNU system, type C-h C-a.
C-c C-y is undefined
Making completion list... [3 times]
Loading /home/leo/github/emacs-document-flow.el/emacs-document.el (source)...
Loading /home/leo/github/emacs-document-flow.el/html2org.el (source)...done
Loading /home/leo/github/emacs-document-flow.el/emacs-document.el (source)...done
Making completion list... [3 times]
_let*: Symbol’s function definition is void: remove-if-not_
Making completion list... [2 times]
You can run the command ‘find-file’ with C-x C-f
let*: Symbol’s function definition is void: remove-if-not
C-M-g is undefined
Quit
Making completion list... [5 times]
Quit
Making completion list...
let*: Symbol’s function definition is void: remove-if-not

**Comment by Faijister** [comment]
When I use the emacs-document-start-translation, it reports:
let*: Symbol’s function definition is void: remove-if-not

**Comment by lujun9972** [comment]
(require 'cl-lib)再试试

**Comment by Faijister** [comment]
emacs M-x list-packages 有个自带的cl-lib
我也尝试下载了一个cl-lib.el 并在启动文件.emacs中加入load-path并(require 'cl-lib)但是还是没有对remove-if-not的定义。你那边这个是在哪个文件中怎么定义的？

**Comment by lujun9972** [comment]
哦，刚查了一下，是cl这个库里的。
emacs自带了cl和cl-lib两个库

**Comment by lujun9972** [comment]
remove-if-not

remove-if-not is an alias for `cl-remove-if-not' in `cl.el'.

(remove-if-not PREDICATE SEQ [KEYWORDVALUE]...)

Remove all items not satisfying PREDICATE in SEQ.
This is a non-destructive function; it makes a copy of SEQ if necessary
to avoid corrupting the original SEQ.

Keywords supported: :key :count :start :end :from-end

**Comment by Faijister** [comment]
cl-lib             1.0           built-in   Common Lisp extensions for Emacs

cl-remove-if-not is an autoloaded compiled Lisp function in
‘cl-seq.el’.

(cl-remove-if-not PREDICATE SEQ [KEYWORD VALUE]...)

Remove all items not satisfying PREDICATE in SEQ.
This is a non-destructive function; it makes a copy of SEQ if necessary
to avoid corrupting the original SEQ.

Keywords supported:  :key :count :start :end :from-end

这个是我工作电脑Windows上Emacs 25上的，晚上回去看看Ubuntu上的，如果也是这样的话我尝试用cl-remove-if-not来试试。

Thanks

**Comment by Faijister** [comment]
在Windows上改成cl-remove-if-not就可以了

cl-remove-if-not: Opening directory: No such file or directory, c:/Users/efuuxii/AppData/Roaming/github/emacs-document/processing/
这个错误说明之前的问题已经解决了，我这边目录没有准备好。

**Comment by lujun9972** [comment]
要先配置一下emacs-document-directory

**Comment by Faijister** [comment]
Ubuntu上改成cl-remove-if-not也可以了。
